disabled_rules:
- conditional_binding_cascade
- line_length
- trailing_comma # doesn't work well as of version 0.13.1
- variable_name
- trailing_newline
- trailing_whitespace
- vertical_whitespace
- weak_delegate # too many false positives (or negatives?)
- todo

statement_position:
statement_mode: uncuddled_else

trailing_whitespace:
ignores_empty_lines: true

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
